module.exports = {
    USERSERV: 'USERSERV',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    FACEBOOK: 'FACEBOOK',
    COLLECTION: {
        USER: 'user'
    },
    DATABASE_ERROR: 'DATABASE_ERROR',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND'
};